import "./globals.css"
import ThemeClient from "@/utils/themes/theme"
import { Box } from "@mui/material"
import ClientStore from "@/store/store"
import { Metadata } from "next"
import AppHeader from "@/components/modules/header/header"
import ScrollTop from "@/components/UI/scroll-top"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <ClientStore>
          <ThemeClient>
            <Box sx={{ bgcolor: "background.default" }} id="root">
              <AppHeader />
              {children}
              <ScrollTop />
            </Box>
          </ThemeClient>
        </ClientStore>
      </body>
    </html>
  )
}
